version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/usr/src/app
    networks:
      - nginx_net
    depends_on:
      - nginx


  nginx:
    image: nginx:1.22.0-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - nginx_net


networks:
  nginx_net:
    driver: bridge